const $=id=>document.getElementById(id);
let backendUrl=localStorage.getItem('martybotBackendUrl')||'';
let token=localStorage.getItem('martybotWebToken')||'';
let apiMode=localStorage.getItem('martybotMode')||'auto';
let haptics=localStorage.getItem('martybotHaptics')!=='false';
let saveChat=localStorage.getItem('martybotSaveChat')!=='false';
let lastStatus=null,lastStatusMode='—',lastTest='—';
const userId='web_user';
const esc=s=>String(s??'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
const now=()=>new Date().toLocaleTimeString('cs-CZ',{hour:'2-digit',minute:'2-digit'});
const tap=()=>{if(haptics&&navigator.vibrate)navigator.vibrate(8)};
function apiBase(){return String(backendUrl||'').trim().replace(/\/+$/,'');}
function headers(json=false){const h={}; if(json)h['Content-Type']='application/json'; if(token)h['X-Agent-Token']=token; return h;}
function toast(msg,type=''){const el=document.createElement('div');el.className='toast'+(type?' '+type:'');el.textContent=msg;$('toasts')?.appendChild(el);setTimeout(()=>el.remove(),3200)}
function md(raw){let t=esc(raw);t=t.replace(/```[\w-]*\n?([\s\S]*?)```/g,(_,c)=>'<pre><code>'+c.trim()+'</code></pre>');t=t.replace(/`([^`\n]+)`/g,'<code>$1</code>');t=t.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');t=t.replace(/^#{1,3} (.+)$/gm,'<h3>$1</h3>');t=t.replace(/\n/g,'<br>');return t;}
function addMsg(role,text){const box=$('messages'); if(!box)return; const wrap=document.createElement('div');wrap.className='msg-wrap '+role;const msg=document.createElement('div');msg.className='msg';msg.innerHTML=md(text);wrap.appendChild(msg);const tm=document.createElement('div');tm.className='msg-time';tm.textContent=now();wrap.appendChild(tm);box.appendChild(wrap);box.scrollTop=box.scrollHeight;}
function setTyping(on){$('typing')?.classList.toggle('on',!!on)}
async function send(text){const input=$('textInput'); const raw=String(text??input?.value??'').trim(); if(!raw)return; tap(); if(input)input.value=''; addMsg('me',raw); setTyping(true); $('sendBtn')&&( $('sendBtn').disabled=true ); try{const r=await fetch(apiBase()+'/api/chat',{method:'POST',headers:headers(true),body:JSON.stringify({text:raw,userId})}); const data=await r.json().catch(()=>({ok:false,replies:['Neplatná odpověď backendu.']})); if(!r.ok)throw new Error(data.error||JSON.stringify(data)); const replies=Array.isArray(data.replies)?data.replies:[data.reply||'Bez odpovědi.']; replies.forEach(x=>addMsg('bot',x)); await refreshStatus();}catch(e){addMsg('sys','Chyba: '+(e.message||String(e)));toast('Chyba spojení','err')}finally{setTyping(false); $('sendBtn')&&($('sendBtn').disabled=false);}}
async function refreshStatus(){try{const r=await fetch(apiBase()+'/api/status',{headers:headers(false)});const s=await r.json();lastStatus=s;lastTest=now();$('avatar')?.classList.toggle('online',!!s.aiAvailable);if($('topStatus')){$('topStatus').textContent=s.aiAvailable?'ONLINE':'OFFLINE';$('topStatus').className='status-pill '+(s.aiAvailable?'':'bad')}if($('statBackend'))$('statBackend').textContent=s.router||'Martybot';if($('statModel'))$('statModel').textContent=s.model||'—';if($('statProvider'))$('statProvider').textContent=s.provider||'—';if($('statAuto'))$('statAuto').textContent=s.fullAgents?'Full agents':'Fallback';fillStatus(s);return s;}catch(e){if($('topStatus')){$('topStatus').textContent='API chyba';$('topStatus').className='status-pill bad'}return null;}}
function fillStatus(s){const rows=[['Mode',s.mode],['Telegram',s.telegramStarted?'ON':s.telegramError||'OFF'],['WhatsApp',s.whatsappMode],['AI',s.aiAvailable?'ON':'OFF'],['Write',s.webSelfImproveWrite?'ON':'OFF'],['Git',s.gitWorkdir||'—']];['statusList','statusListDashboard','statusListMobile'].forEach(id=>{const el=$(id); if(!el)return; el.innerHTML=rows.map(([k,v])=>`<div class="st-row"><span class="k">${esc(k)}</span><span class="v">${esc(v)}</span></div>`).join('');}); if($('dashMode'))$('dashMode').textContent=s.mode||'—'; if($('dashTools'))$('dashTools').textContent=s.fullAgents?'ON':'OFF'; if($('dashMemory'))$('dashMemory').textContent='JSON/Supabase'; if($('dashLast'))$('dashLast').textContent=lastTest;}
function saveSettings(){backendUrl=($('backendInput')?.value||$('backendInputMobile')?.value||'').trim();token=($('tokenInput')?.value||$('tokenInputMobile')?.value||'').trim();apiMode=($('modeInput')?.value||$('modeInputMobile')?.value||'auto');localStorage.setItem('martybotBackendUrl',backendUrl);localStorage.setItem('martybotWebToken',token);localStorage.setItem('martybotMode',apiMode);syncInputs();toast('Spojení uloženo','ok');refreshStatus();}
function syncInputs(){['backendInput','backendInputMobile'].forEach(id=>{$(id)&&($(id).value=backendUrl)});['tokenInput','tokenInputMobile'].forEach(id=>{$(id)&&($(id).value=token)});['modeInput','modeInputMobile'].forEach(id=>{$(id)&&($(id).value=apiMode)});}
function switchTab(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('view-'+name)?.classList.add('active');document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
function init(){syncInputs();$('sendBtn')?.addEventListener('click',()=>send());$('textInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}});$('refreshBtn')?.addEventListener('click',refreshStatus);$('clearBtn')?.addEventListener('click',()=>{$('messages').innerHTML='';addMsg('sys','Chat smazán lokálně.')});$('saveSettings')?.addEventListener('click',saveSettings);$('saveSettingsMobile')?.addEventListener('click',saveSettings);$('testMobileBtn')?.addEventListener('click',refreshStatus);document.querySelectorAll('[data-cmd]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.cmd)));document.querySelectorAll('.tabbar button').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));refreshStatus();setInterval(refreshStatus,20000);}
document.addEventListener('DOMContentLoaded',init);
window.toast=toast;
window.martybotSend=send;
